---
title: "Task 22"
author: "Exode"
date: "7/4/2020"
output: 
  html_document:
    keep_md: true
---

```{r include=FALSE}
library(sf)
library(ggplot2)
library(haven)
library(foreign)
library(rgdal)
library(raster)
library(stringi)
library(stringr)
library(DT)
library(dplyr)
library(readr)
library(ggrepel)
```


```{r}
r2<-st_read("C:/Users/exoni/Downloads/Wells-shp")

```

```{r}
k<-st_read("C:/Users/exoni/Downloads/Dams_of_Idaho-shp/Dams_of_Idaho.shp")

k1 <-subset(k,SurfaceAre>50)

```
```{r}
"C:/Users/exoni/Downloads/hyd250"
download.file("https://research.idwr.idaho.gov/gis/Spatial/Hydrography/streams_lakes/c_250k/hyd250.zip", 
              destfile = "water.zip" , mode='wb')
unzip("water.zip", exdir = ".")
r5<-st_read("./hyd250.shp" )
```

```{r}

ID_counties <- USAboundaries::us_counties(states = "ID")
st_crs(ID_counties)
my_proj <- "+proj=moll +lat_0=45 +lon_0=-115 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
idaho_tr <- ID_counties %>% st_transform( crs = my_proj)

```

```{r}
r6 <- subset(r5, FEAT_NAME=="Snake River"|FEAT_NAME=="Henrys Fork")
r7<-subset(r2,Production>=5000)
ggplot() + 
  geom_sf(data = idaho_tr, size = 1, color = "black", fill = "cyan1") + 
  ggtitle("IDaho: Rivers, Wells, and Dams") + 
  coord_sf() + geom_sf(data=r6,aes(label=FEAT_NAME,geometry=geometry,color=FEAT_NAME),size=3)+geom_sf(data=r7,aes(size=Production,geometry=geometry))+theme_bw() +
  theme(panel.grid = element_line(colour = "transparent"),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10))+geom_sf(data=k1,aes(fill=SurfaceAre,geometry=geometry),color="blue")+labs(size="Production Rate (in Gallons)",fill="Surface Area (in Acres)",color="River Name")

```
```{r}
ggsave('~/saved_image.png', width = 45, height = 40, dpi = 200)
```

